import type { AgentResult, DemoScenario } from '@/types';

export const fallbackAgentResult: AgentResult = {
  risk_score: 85,
  user_profile: 'kararsiz',
  intervention_required: true,
  source_status: 'fallback',
  latency_ms: 42,
  final_message:
    'BUFF Aura Watch Pro ile Pulse Watch Air arasinda kaldiginizi fark ettik. CART15 kodu 15 dakika boyunca size ozel indirim saglar. Premium sensore ihtiyaciniz varsa Aura, fiyat/performans istiyorsaniz Pulse daha iyi secim.',
  coupon_details: {
    coupon_code: 'CART15',
    discount_ratio: 0.15,
    discount_amount: 4499.7,
    new_total: 25498.3,
    expires_in_minutes: 15,
    margin_protection_triggered: false,
  },
  comparison_data: {
    comparison_found: true,
    verdict:
      'Aura Watch Pro titanyum kasa, microLED ekran ve gelismis sensorler icin; Pulse Watch Air ise hafiflik ve fiyat/performans icin daha uygundur.',
  },
  workflow_events: [
    'Telemetry captured',
    'Analyst fallback risk: 85/100 (kararsiz)',
    'Router selected intervention path',
    'Strategist selected intervention + coupon CART15 + comparison',
    'Synthesizer prepared popup message',
  ],
  tool_calls: [
    'get_user_abandonment_history',
    'get_product_comparison_details',
    'generate_dynamic_coupon',
  ],
  model_trace: [
    {
      agent: 'Analyst',
      status: 'fallback',
      latency_ms: 14,
      detail: 'Deterministic risk heuristic used.',
    },
    {
      agent: 'Strategist',
      status: 'fallback',
      latency_ms: 12,
      detail: 'Rule-based strategy selected.',
    },
    {
      agent: 'Synthesizer',
      status: 'fallback',
      latency_ms: 16,
      detail: 'Static popup copy used.',
    },
  ],
  business_impact: {
    cart_total: 29998,
    discount_amount: 4499.7,
    new_total: 25498.3,
    recovered_revenue: 25498.3,
    monthly_recovery_projection: 1070928.6,
    avoided_unnecessary_popup: false,
  },
  guardrails: {
    risk_threshold: 60,
    max_discount_ratio: 0.2,
    margin_protection_triggered: false,
  },
  automation: {
    provider: 'n8n',
    configured: false,
    triggered: false,
    status: 'ready',
    detail: 'N8N_WEBHOOK_URL tanimlaninca cart rescue otomasyonu tetiklenir.',
  },
};

export const scenarioFallbackResults: Record<DemoScenario, AgentResult> = {
  'price-sensitive': {
    risk_score: 91,
    user_profile: 'fiyat duyarli',
    intervention_required: true,
    source_status: 'fallback',
    latency_ms: 39,
    final_message:
      'BUFF sepetiniz icin CART15 kodunu hazirladik. Bu teklif 15 dakika gecerli ve toplam tutarda 4.499 TL avantaj saglar. Hazirsaniz siparisi birlikte tamamlayalim.',
    coupon_details: {
      coupon_code: 'CART15',
      discount_ratio: 0.15,
      discount_amount: 4499.7,
      new_total: 25498.3,
      expires_in_minutes: 15,
      margin_protection_triggered: false,
    },
    comparison_data: null,
    workflow_events: [
      'Telemetry captured',
      'Analyst calculated risk: 91/100 (fiyat duyarli)',
      'Router selected intervention path',
      'Strategist selected intervention + coupon CART15',
      'Synthesizer prepared popup message',
    ],
    tool_calls: ['get_user_abandonment_history', 'generate_dynamic_coupon'],
    model_trace: fallbackAgentResult.model_trace,
    business_impact: {
      cart_total: 29998,
      discount_amount: 4499.7,
      new_total: 25498.3,
      recovered_revenue: 25498.3,
      monthly_recovery_projection: 1070928.6,
      avoided_unnecessary_popup: false,
    },
    guardrails: {
      risk_threshold: 60,
      max_discount_ratio: 0.2,
      margin_protection_triggered: false,
    },
    automation: fallbackAgentResult.automation,
  },
  dilemma: fallbackAgentResult,
  'low-risk': {
    risk_score: 28,
    user_profile: 'odaklanmis',
    intervention_required: false,
    source_status: 'fallback',
    latency_ms: 18,
    final_message:
      'Risk dusuk oldugu icin BUFF Store kullaniciyi rahatsiz etmedi.',
    coupon_details: null,
    comparison_data: null,
    workflow_events: [
      'Telemetry captured',
      'Analyst calculated risk: 28/100 (odaklanmis)',
      'Router ended workflow: no intervention',
    ],
    tool_calls: ['get_user_abandonment_history'],
    model_trace: [
      {
        agent: 'Analyst',
        status: 'fallback',
        latency_ms: 18,
        detail: 'Deterministic risk heuristic used.',
      },
    ],
    business_impact: {
      cart_total: 29998,
      discount_amount: 0,
      new_total: 29998,
      recovered_revenue: 0,
      monthly_recovery_projection: 0,
      avoided_unnecessary_popup: true,
    },
    guardrails: {
      risk_threshold: 60,
      max_discount_ratio: 0.2,
      margin_protection_triggered: false,
    },
    automation: {
      provider: 'n8n',
      configured: false,
      triggered: false,
      status: 'skipped',
      detail: 'Dusuk riskte otomasyon tetiklenmez.',
    },
  },
  'margin-guardrail': {
    risk_score: 98,
    user_profile: 'fiyat duyarli',
    intervention_required: true,
    source_status: 'fallback',
    latency_ms: 44,
    final_message:
      'Terk riski cok yuksek oldugu icin daha guclu bir teklif denendi, ancak marj koruma indirimi CART20 ile sinirladi. Bu teklif 15 dakika gecerli ve sepetinizi zararli kampanyaya donusturmeden kurtarmayi hedefler.',
    coupon_details: {
      coupon_code: 'CART20',
      discount_ratio: 0.2,
      discount_amount: 5999.6,
      new_total: 23998.4,
      expires_in_minutes: 15,
      margin_protection_triggered: true,
    },
    comparison_data: null,
    workflow_events: [
      'Telemetry captured',
      'Analyst calculated risk: 98/100 (fiyat duyarli)',
      'Router selected intervention path',
      'Strategist selected intervention + coupon CART20',
      'Margin guardrail capped requested discount at 20%',
      'Synthesizer prepared popup message',
    ],
    tool_calls: ['get_user_abandonment_history', 'generate_dynamic_coupon'],
    model_trace: fallbackAgentResult.model_trace,
    business_impact: {
      cart_total: 29998,
      discount_amount: 5999.6,
      new_total: 23998.4,
      recovered_revenue: 23998.4,
      monthly_recovery_projection: 1007932.8,
      avoided_unnecessary_popup: false,
    },
    guardrails: {
      risk_threshold: 60,
      max_discount_ratio: 0.2,
      margin_protection_triggered: true,
    },
    automation: fallbackAgentResult.automation,
  },
};
